require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StockInBillsController do
  login_admin
  let(:warehouse) { FactoryGirl.create(:seller,:account_id => current_account.id) }
  let(:stock_in_bill) {FactoryGirl.create(:stock_in_bill,:account_id => current_account.id,:seller_id => warehouse.id)}
  let(:sku) { create(:sku,:account_id => current_account.id) }
  before(:each) { @stock_in_bill = stock_in_bill }
  # This should return the minimal set of attributes required to create a valid
  # StockInBill. As you add validations to StockInBill, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {stock_type: "IOT", bill_products_attributes: { "0" => {sku_id: sku.id, number: 10, price: 10.0, real_number: 1, total_price: 100.0 }}}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StockInBillsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all stock_in_bills as @stock_in_bills" do
      get :index,{:warehouse_id => warehouse}, valid_session
      assigns(:bills).should eq([stock_in_bill])
    end
  end

  describe "GET show" do
    it "assigns the requested stock_in_bill as @stock_in_bill" do
      get :show, {:warehouse_id => warehouse,:id => stock_in_bill.to_param}, valid_session
      assigns(:bill).should eq(stock_in_bill)
    end
  end

  describe "GET new" do
    it "assigns a new stock_in_bill as @stock_in_bill" do
      warehouse.save
      get :new, {:warehouse_id => warehouse}, valid_session
      assigns(:bill).should be_a_new(StockInBill)
    end
  end

  describe "GET edit" do
    it "assigns the requested stock_in_bill as @stock_in_bill" do
      get :edit, {:warehouse_id => warehouse,:id => stock_in_bill.to_param}, valid_session
      assigns(:bill).should eq(stock_in_bill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StockInBill" do
        expect {
          post :create, {:warehouse_id => warehouse,:stock_in_bill => valid_attributes}, valid_session
        }.to change(StockInBill, :count).by(1)
      end

      it "assigns a newly created stock_in_bill as @stock_in_bill" do
        post :create, {:warehouse_id => warehouse,:stock_in_bill => valid_attributes}, valid_session
        assigns(:bill).should be_a(StockInBill)
        assigns(:bill).should be_persisted
      end

      it "redirects to the created stock_in_bill" do
        post :create, {:warehouse_id => warehouse,:stock_in_bill => valid_attributes}, valid_session
        response.should redirect_to(warehouse_stock_in_bill_path(warehouse,StockInBill.last))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stock_in_bill as @stock_in_bill" do
        # Trigger the behavior that occurs when invalid params are submitted
        StockInBill.any_instance.stub(:save).and_return(false)

        post :create, {:warehouse_id => warehouse,:stock_in_bill => {  }}, valid_session
        assigns(:bill).should be_a_new(StockInBill)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StockInBill.any_instance.stub(:save).and_return(false)
        post :create, {:warehouse_id => warehouse,:stock_in_bill => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested stock_in_bill" do
        # Assuming there are no other stock_in_bills in the database, this
        # specifies that the StockInBill created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StockInBill.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:warehouse_id => warehouse,:id => stock_in_bill.to_param, :stock_in_bill => { "these" => "params" }}, valid_session
      end

      it "assigns the requested stock_in_bill as @stock_in_bill" do
        put :update, {:warehouse_id => warehouse,:id => stock_in_bill.to_param, :stock_in_bill => valid_attributes}, valid_session
        assigns(:bill).should eq(stock_in_bill)
      end

      it "redirects to the stock_in_bill" do
        put :update, {:warehouse_id => warehouse,:id => stock_in_bill.to_param, :stock_in_bill => valid_attributes}, valid_session
        response.should redirect_to(warehouse_stock_in_bill_path(warehouse,stock_in_bill))
      end
    end

    describe "with invalid params" do
      it "assigns the stock_in_bill as @stock_in_bill" do
        # Trigger the behavior that occurs when invalid params are submitted
        StockInBill.any_instance.stub(:save).and_return(false)
        put :update, {:warehouse_id => warehouse,:id => stock_in_bill.to_param, :stock_in_bill => {  }}, valid_session
        assigns(:bill).should eq(stock_in_bill)
      end

      it "re-renders the 'edit' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StockInBill.any_instance.stub(:save).and_return(false)
        put :update, {:warehouse_id => warehouse,:id => stock_in_bill.to_param, :stock_in_bill => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

end
