require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TradeSearchesController do

  # This should return the minimal set of attributes required to create a valid
  # TradeSearch. As you add validations to TradeSearch, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TradeSearchesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all trade_searches as @trade_searches" do
      trade_search = TradeSearch.create! valid_attributes
      get :index, {}, valid_session
      assigns(:trade_searches).should eq([trade_search])
    end
  end

  describe "GET show" do
    it "assigns the requested trade_search as @trade_search" do
      trade_search = TradeSearch.create! valid_attributes
      get :show, {:id => trade_search.to_param}, valid_session
      assigns(:trade_search).should eq(trade_search)
    end
  end

  describe "GET new" do
    it "assigns a new trade_search as @trade_search" do
      get :new, {}, valid_session
      assigns(:trade_search).should be_a_new(TradeSearch)
    end
  end

  describe "GET edit" do
    it "assigns the requested trade_search as @trade_search" do
      trade_search = TradeSearch.create! valid_attributes
      get :edit, {:id => trade_search.to_param}, valid_session
      assigns(:trade_search).should eq(trade_search)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TradeSearch" do
        expect {
          post :create, {:trade_search => valid_attributes}, valid_session
        }.to change(TradeSearch, :count).by(1)
      end

      it "assigns a newly created trade_search as @trade_search" do
        post :create, {:trade_search => valid_attributes}, valid_session
        assigns(:trade_search).should be_a(TradeSearch)
        assigns(:trade_search).should be_persisted
      end

      it "redirects to the created trade_search" do
        post :create, {:trade_search => valid_attributes}, valid_session
        response.should redirect_to(TradeSearch.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved trade_search as @trade_search" do
        # Trigger the behavior that occurs when invalid params are submitted
        TradeSearch.any_instance.stub(:save).and_return(false)
        post :create, {:trade_search => {  }}, valid_session
        assigns(:trade_search).should be_a_new(TradeSearch)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TradeSearch.any_instance.stub(:save).and_return(false)
        post :create, {:trade_search => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested trade_search" do
        trade_search = TradeSearch.create! valid_attributes
        # Assuming there are no other trade_searches in the database, this
        # specifies that the TradeSearch created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TradeSearch.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => trade_search.to_param, :trade_search => { "these" => "params" }}, valid_session
      end

      it "assigns the requested trade_search as @trade_search" do
        trade_search = TradeSearch.create! valid_attributes
        put :update, {:id => trade_search.to_param, :trade_search => valid_attributes}, valid_session
        assigns(:trade_search).should eq(trade_search)
      end

      it "redirects to the trade_search" do
        trade_search = TradeSearch.create! valid_attributes
        put :update, {:id => trade_search.to_param, :trade_search => valid_attributes}, valid_session
        response.should redirect_to(trade_search)
      end
    end

    describe "with invalid params" do
      it "assigns the trade_search as @trade_search" do
        trade_search = TradeSearch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TradeSearch.any_instance.stub(:save).and_return(false)
        put :update, {:id => trade_search.to_param, :trade_search => {  }}, valid_session
        assigns(:trade_search).should eq(trade_search)
      end

      it "re-renders the 'edit' template" do
        trade_search = TradeSearch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TradeSearch.any_instance.stub(:save).and_return(false)
        put :update, {:id => trade_search.to_param, :trade_search => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested trade_search" do
      trade_search = TradeSearch.create! valid_attributes
      expect {
        delete :destroy, {:id => trade_search.to_param}, valid_session
      }.to change(TradeSearch, :count).by(-1)
    end

    it "redirects to the trade_searches list" do
      trade_search = TradeSearch.create! valid_attributes
      delete :destroy, {:id => trade_search.to_param}, valid_session
      response.should redirect_to(trade_searches_url)
    end
  end

end
